steps:
    - name: gcr.io/cloud-builders/git
      secretEnv: ["GITHUB_TOKEN"]
      entrypoint: "bash"
      args:
          - -c
          - |
              echo "$$GITHUB_TOKEN" >> /root/token
              cp -r /root/ /workspace/
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - "-t"
          - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
          - .
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      args:
          - run
          - deploy
          - "$REPO_NAME"
          - "--image"
          - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
          - "--region"
          - us-central1
          - "--set-env-vars=ENVIRONMENT=PRODUCTION"
          - "--timeout=600"
          - "--memory=128Mi"
          - "--min-instances=0"
          - >-
              --service-account=service-video-maker@$PROJECT_ID.iam.gserviceaccount.com
          - "--cpu=1"
          - "--concurrency=120"
          - "--allow-unauthenticated"
      entrypoint: gcloud
images:
    - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"

availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
          env: "GITHUB_TOKEN"
