apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: service-video-maker
    namespace: "847778980696"
    selfLink: /apis/serving.knative.dev/v1/namespaces/847778980696/services/service-video-maker
    uid: 240cf604-8de4-4121-8434-8d8737c0f7a4
    resourceVersion: AAYt+b6E8QY
    generation: 3
    creationTimestamp: "2025-02-12T22:44:17.717163Z"
    labels:
        commit-sha: 31b133bae65103f8f2c011f92c8bec282c093fdd
        gcb-build-id: de7eed86-abff-4aef-a549-fabbff3210a3
        gcb-trigger-id: 88ce2998-d55d-4432-b706-c71fd85203be
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        cloud.googleapis.com/location: us-central1
    annotations:
        serving.knative.dev/creator: guilhermesccaporali@gmail.com
        serving.knative.dev/lastModifier: 847778980696-compute@developer.gserviceaccount.com
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 510.0.0
        run.googleapis.com/launch-stage: BETA
        run.googleapis.com/operation-id: f1dc5874-0a7f-445c-b326-57de91815613
        run.googleapis.com/ingress: all
        run.googleapis.com/ingress-status: all
        run.googleapis.com/scalingMode: manual
        run.googleapis.com/manualInstanceCount: "1"
        run.googleapis.com/urls: '["https://service-video-maker-847778980696.us-central1.run.app","https://service-video-maker-y4l2xguz3a-uc.a.run.app"]'
spec:
    template:
        metadata:
            labels:
                client.knative.dev/nonce: auvbribput
                commit-sha: 31b133bae65103f8f2c011f92c8bec282c093fdd
                gcb-build-id: de7eed86-abff-4aef-a549-fabbff3210a3
                gcb-trigger-id: 88ce2998-d55d-4432-b706-c71fd85203be
                gcb-trigger-region: global
                managed-by: gcp-cloud-build-deploy-cloud-run
                run.googleapis.com/startupProbeType: Default
            annotations:
                autoscaling.knative.dev/maxScale: "10"
                run.googleapis.com/client-name: gcloud
                run.googleapis.com/client-version: 510.0.0
                run.googleapis.com/startup-cpu-boost: "true"
        spec:
            containerConcurrency: 80
            timeoutSeconds: 300
            serviceAccountName: 847778980696-compute@developer.gserviceaccount.com
            containers:
                - name: placeholder-1
                  image: us-central1-docker.pkg.dev/youtube-shorts-448712/cloud-run-source-deploy/service-video-maker/service-video-maker:31b133bae65103f8f2c011f92c8bec282c093fdd
                  ports:
                      - name: http1
                        containerPort: 8080
                  resources:
                      limits:
                          cpu: 1000m
                          memory: 128Mi
                  startupProbe:
                      timeoutSeconds: 240
                      periodSeconds: 240
                      failureThreshold: 1
                      tcpSocket:
                          port: 8080
    traffic:
        - percent: 100
          latestRevision: true
status:
    observedGeneration: 3
    conditions:
        - type: Ready
          status: "True"
          lastTransitionTime: "2025-02-12T22:48:46.754054Z"
        - type: ConfigurationsReady
          status: "True"
          lastTransitionTime: "2025-02-12T22:48:45.478922Z"
        - type: RoutesReady
          status: "True"
          lastTransitionTime: "2025-02-12T22:48:46.718233Z"
    latestReadyRevisionName: service-video-maker-00002-qww
    latestCreatedRevisionName: service-video-maker-00002-qww
    traffic:
        - revisionName: service-video-maker-00002-qww
          percent: 100
          latestRevision: true
    url: https://service-video-maker-y4l2xguz3a-uc.a.run.app
    address:
        url: https://service-video-maker-y4l2xguz3a-uc.a.run.app
