steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_REPO_NAME:$COMMIT_SHA",
              ".",
          ]

    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "push",
              "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_REPO_NAME:$COMMIT_SHA",
          ]

    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      args:
          - "run"
          - "deploy"
          - $_REPO_NAME
          - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_REPO_NAME:$COMMIT_SHA"
          - "--region=us-central1"
          - "--set-env-vars=ENVIRONMENT=PRODUCTION"
          - "--platform=managed"
          - "--allow-unauthenticated"
          - "--memory=128Mi"
          - "--concurrency=120"
          - "--timeout=600"

images:
    - "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_REPO_NAME:$COMMIT_SHA"
